-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.LENGTH = (SELECT MAX(LENGTH)
                  FROM FISH_INFO f
                  WHERE i.FISH_TYPE = f.FISH_TYPE)
ORDER BY ID ASC;